---
# tasks file for apigee-opdk-setup-os-common-extra
- block:
  - name: Update toubleshooting OS packages
    become: yes
    yum:
      name: "{{ item }}"
      state: present
    with_items:
    - lsof
    - nc
    - dos2unix
    - tcpdump
    - tree
    - telnet
    - vim

  rescue:

    - name: expose baseurl in epel.repo definition
      replace:
         backup: yes
         regexp: '^(#baseurl=)(.*)'
         replace: 'baseurl=\2'
         dest: /etc/yum.repos.d/epel.repo"

    - name: remove mirrorlist in epel.repo definition
      replace:
         backup: yes
         regexp: '^(mirrorlist=)(.*)'
         replace: '#mirrorlist=\2'
         dest: /etc/yum.repos.d/epel.repo"

    - name: Update toubleshooting OS packages
      become: yes
      yum:
        name: "{{ item }}"
        state: present
      with_items:
      - lsof
      - nc
      - dos2unix
      - tcpdump
      - tree
      - telnet
      - vim

    - name: remove  baseurl in epel.repo definition
      replace:
         backup: yes
         regexp: '^(baseurl=)(.*)'
         replace: '#baseurl=\2'
         dest: /etc/yum.repos.d/epel.repo"

    - name: expose mirrorlist in epel.repo definition
      replace:
         backup: yes
         regexp: '^(#mirrorlist=)(.*)'
         replace: 'mirrorlist=\2'
         dest: /etc/yum.repos.d/epel.repo"

