---
# tasks file for apigee-opdk-setup-os-common-extra
#- block:
- name: Update toubleshooting OS packages
  become: yes
  yum:
    name: "{{ item }}"
    state: present
  with_items:
  - lsof
  - nc
  - dos2unix
  - tcpdump
  - tree
  - telnet
  - vim
