---
# tasks file for apigee-opdk-setup-os-common-extra
#- block:
- name: Update yum os packages
  yum:
    name: "{{ item }}"
    state: present
  with_items:
  - bind-utils
  - chkconfig
  - curl
  - sudo
  - tar
  - wget
  - yum-utils
  - grep
  - rpm
  - sed
  - sudo
  - unzip
  - rsync
  - which
  - lsof
  - nc
  - dos2unix
  - tcpdump
  - tree
  - telnet
  - vim
