---
- block:

  - name: Update troubleshooting OS packages
    become: yes
    yum:
      name: "{{ item }}"
      state: present
    with_items: "{{ os_packages }}"
    environment:
      http_proxy: "{{ http_proxy }}"
      https_proxy: "{{ https_proxy }}"
      no_proxy: "{{ no_proxy }}"

  rescue:

    - name: Check for existence of epel.repo
      stat:
        path: /etc/yum.repos.d/epel.repo
      register: epel

    - block:

      - name: expose baseurl in epel.repo definition
        replace:
           backup: yes
           regexp: '^(#baseurl=)(.*)'
           replace: 'baseurl=\2'
           dest: '/etc/yum.repos.d/epel.repo'

      - name: remove mirrorlist in epel.repo definition
        replace:
           backup: yes
           regexp: '^(mirrorlist=)(.*)'
           replace: '#mirrorlist=\2'
           dest: /etc/yum.repos.d/epel.repo

      when: epel.stat.exists

    - name: Update troubleshooting OS packages
      become: yes
      yum:
        name: "{{ item }}"
        state: present
      with_items: "{{ os_packages }}"
      environment:
        http_proxy: "{{ http_proxy }}"
        https_proxy: "{{ https_proxy }}"
        no_proxy: "{{ no_proxy }}"
